# https://taskfile.dev

version: '3'

includes:
  tf: ./tasks/terraform.yml
  releases: ./tasks/helmfile.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
