checkov: &checkov
  step:
    name: Checkov
    image:
      name: bridgecrew/checkov:latest
      entrypoint:
        - "/usr/bin/env"
        - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    script:
      - checkov -d .

pipelines:
  default:
    - step:
        name: "Terraform Validate"
        image:
          name: hashicorp/terraform:light
        script:
          - cd dev/us-east-1
          - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - terraform init
          - terraform validate
    - <<: *checkov
    - step:
        name: "Terraform Plan"
        image:
          name: hashicorp/terraform:light
        script:
          - cd dev/us-east-1
          - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - terraform init
          - terraform plan
    - step:
        name: "Terraform Apply"
        trigger: manual
        image:
          name: hashicorp/terraform:light
        script:
          - cd dev/us-east-1
          - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - terraform init
          - terraform apply -auto-approve
    - step:
        name: "Slack"
        script:
          - pipe: atlassian/slack-notify:1.0.0
            variables:
              WEBHOOK_URL: $SLACK_WEBHOOK
              MESSAGE: "terraform-templates >> dev >> us-east-1"
